### ISSUE TITLE
Visualize more ground bots

### ISSUE THREAD

**Issue by sourishg** [quadrotor-IITKgp/iarc7_simulator#1]
Currently, three ground bots (with 2 obstacle bots) and the quad is visualized in the simulator. We want to display all the bots. So this would be a perfect way to get familiarized with the Qt and ROS integration done in the simulator.

@shubhika03 and @anveenaik99 your task is to add another ground bot. Just follow the patterns in the code structure, it should be easy. You both should work together on this. Send a PR after you're done.

Ping me if you have doubts.

**Comment by sourishg** [comment]
@shubhika03 and @anveenaik99 could you guys figure this out?

**Comment by shubhika03** [comment]
It will take us some more time to understand it.

**Comment by shubhika03** [comment]
@sourishg we have added all the bots  and sent a pull requaest. Please look into that.
